"use client";

import { useCallback,useEffect,useMemo,useState } from "react";
import { createPortal } from "react-dom";

type Service={id:number;name:string;priceCents:number;durationMin:number};
type Product={id:number;name:string;description?:string;priceCents:number;stock:number;imageKey?:string};
type Collaborator={id:number;name:string;active:boolean};
type Profile={name?:string;phone?:string;birthDate?:string}|null;
type Data={services:Service[];products:Product[];collaborators:Collaborator[];profile:Profile;occupiedTimes?:string[]};
type Journey="booking"|"products"|"";
type Step="home"|"services"|"professional"|"datetime"|"details"|"products"|"summary";

const EMPTY:Data={services:[],products:[],collaborators:[],profile:null,occupiedTimes:[]};
function localDateKey(date=new Date()){
  const parts=new Intl.DateTimeFormat("en-CA",{timeZone:"America/Sao_Paulo",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(date);
  const year=parts.find(part=>part.type==="year")?.value||"";
  const month=parts.find(part=>part.type==="month")?.value||"";
  const day=parts.find(part=>part.type==="day")?.value||"";
  return `${year}-${month}-${day}`;
}
function localMinutesNow(){
  const parts=new Intl.DateTimeFormat("en-US",{timeZone:"America/Sao_Paulo",hour:"2-digit",minute:"2-digit",hour12:false}).formatToParts(new Date());
  const hour=Number(parts.find(part=>part.type==="hour")?.value||0);
  const minute=Number(parts.find(part=>part.type==="minute")?.value||0);
  return hour*60+minute;
}
function money(cents:number){return new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format((Number(cents)||0)/100)}
function storedImage(key?:string){return key?`/api/upload?key=${encodeURIComponent(key)}`:""}
function slotsFor(date:string,duration:number){if(!date)return[];const day=new Date(`${date}T12:00:00`).getDay();const start=day===0||day===6?8*60:18*60;const end=day===0?12*60:20*60+30;const today=localDateKey();const current=localMinutesNow();const out:string[]=[];for(let m=start;m+duration<=end;m+=30){if(date===today&&m<=current)continue;out.push(`${String(Math.floor(m/60)).padStart(2,"0")}:${String(m%60).padStart(2,"0")}`)}return out}

export default function BookingV3(){
  const [target,setTarget]=useState<HTMLElement|null>(null);
  useEffect(()=>{const sync=()=>setTarget(document.querySelector<HTMLElement>(".booking-with-ads"));sync();const o=new MutationObserver(sync);o.observe(document.body,{childList:true,subtree:true});return()=>o.disconnect()},[]);
  return target?createPortal(<Flow/>,target):null;
}

function Flow(){
  const [data,setData]=useState<Data>(EMPTY);const[loading,setLoading]=useState(true);const[journey,setJourney]=useState<Journey>("");const[step,setStep]=useState<Step>("home");const[selectedServices,setSelectedServices]=useState<number[]>([]);const[collaboratorId,setCollaboratorId]=useState(0);const[date,setDate]=useState("");const[time,setTime]=useState("");const[cart,setCart]=useState<Record<number,number>>({});const[details,setDetails]=useState({name:"",phone:"",birthDate:""});const[occupied,setOccupied]=useState<string[]>([]);const[message,setMessage]=useState("");const[submitting,setSubmitting]=useState(false);
  useEffect(()=>{
    if(journey!=="booking"||step!=="summary"||!date)return;
    const today=localDateKey();
    const [hours,minutes]=time.split(":").map(Number);
    const pastDate=date<today;
    const pastTime=date===today&&Number.isFinite(hours)&&Number.isFinite(minutes)&&hours*60+minutes<=localMinutesNow();
    if(!pastDate&&!pastTime)return;
    setDate(pastDate?"":date);
    setTime("");
    setStep("datetime");
    setMessage(pastDate?"A data escolhida já passou. Escolha uma nova data.":"Este horário já passou. Escolha outro horário.");
  },[journey,step,date,time]);
  const load=useCallback(async()=>{try{const r=await fetch("/api/booking-v3",{cache:"no-store"});const b=await r.json();if(!r.ok)throw new Error(b.error||"Não foi possível carregar.");setData({services:b.services||[],products:b.products||[],collaborators:b.collaborators||[],profile:b.profile||null});setDetails({name:b.profile?.name||"",phone:b.profile?.phone||"",birthDate:b.profile?.birthDate||""});if((b.collaborators||[]).length===1)setCollaboratorId(b.collaborators[0].id);}catch(e){setMessage(e instanceof Error?e.message:"Não foi possível carregar.")}finally{setLoading(false)}},[]);useEffect(()=>{const timer=window.setTimeout(()=>{void load()},0);return()=>window.clearTimeout(timer)},[load]);
  const services=useMemo(()=>data.services.filter(s=>selectedServices.includes(s.id)),[data.services,selectedServices]);const totalDuration=services.reduce((s,i)=>s+i.durationMin,0);const serviceTotal=services.reduce((s,i)=>s+i.priceCents,0);const cartItems=useMemo(()=>data.products.map(p=>({product:p,quantity:cart[p.id]||0})).filter(i=>i.quantity>0),[data.products,cart]);const productTotal=cartItems.reduce((s,i)=>s+i.product.priceCents*i.quantity,0);const availableTimes=slotsFor(date,totalDuration||30).filter(t=>!occupied.includes(t));
  useEffect(()=>{if(step!=="datetime"||!date||!selectedServices.length)return;const q=new URLSearchParams({date,serviceIds:selectedServices.join(",")});if(collaboratorId)q.set("collaboratorId",String(collaboratorId));fetch(`/api/booking-v3?${q}`,{cache:"no-store"}).then(r=>r.json()).then(b=>setOccupied(Array.isArray(b.occupiedTimes)?b.occupiedTimes:[])).catch(()=>setMessage("Não foi possível conferir os horários."))},[date,selectedServices,collaboratorId,step]);
  function home(){setJourney("");setStep("home");setSelectedServices([]);setDate("");setTime("");setCart({});setMessage("")}
  function toggleService(id:number){setSelectedServices(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);setTime("")}
  function updateProduct(p:Product,delta:number){setCart(c=>{const next=Math.max(0,Math.min(p.stock,(c[p.id]||0)+delta));const copy={...c};if(next)copy[p.id]=next;else delete copy[p.id];return copy})}
  const back=()=>{if(step==="services")home();else if(step==="professional")setStep("services");else if(step==="datetime")setStep("professional");else if(step==="details")setStep(journey==="products"?"products":"datetime");else if(step==="products")home();else if(step==="summary")setStep("details")};
  async function finish(){setMessage("");setSubmitting(true);try{if(journey==="booking"){const r=await fetch("/api/booking-v3",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"appointment",serviceIds:selectedServices,collaboratorId:collaboratorId||undefined,date,time,clientName:details.name,phone:details.phone,birthDate:details.birthDate})});const b=await r.json();if(!r.ok)throw new Error(b.error||"Não foi possível agendar.");const text=`Olá, Yuri! Gostaria de confirmar meu agendamento.\n\nServiços: ${services.map(s=>s.name).join(" + ")}\nDuração total: ${totalDuration} min\nValor: ${money(serviceTotal)}\nData: ${new Date(`${date}T12:00:00`).toLocaleDateString("pt-BR")}\nHorário: ${time}\nProfissional: ${data.collaborators.find(c=>c.id===collaboratorId)?.name||"Qualquer disponível"}\nCliente: ${details.name}\nProtocolo: #${b.appointment?.id||""}`;window.open(`https://wa.me/5562981007636?text=${encodeURIComponent(text)}`,"_blank","noopener,noreferrer");home();}
      else{const r=await fetch("/api/product-orders",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"create",items:cartItems.map(i=>({id:i.product.id,quantity:i.quantity})),clientName:details.name,phone:details.phone,birthDate:details.birthDate})});const b=await r.json();if(!r.ok)throw new Error(b.error||"Não foi possível registrar o pedido.");const text=`Olá, Yuri! Gostaria de encomendar:\n\n${cartItems.map(i=>`${i.quantity}x ${i.product.name} — ${money(i.product.priceCents*i.quantity)}`).join("\n")}\n\nTotal: ${money(productTotal)}\nCliente: ${details.name}\nPedido: #${b.order?.id||""}`;window.open(`https://wa.me/5562981007636?text=${encodeURIComponent(text)}`,"_blank","noopener,noreferrer");home();}}
    catch(e){setMessage(e instanceof Error?e.message:"Não foi possível concluir.")}finally{setSubmitting(false)}}
  if(loading)return <section className="mobile-booking-app booking-commerce-app booking-hub-v2 booking-v3 loading" aria-label="Central de agendamento Yuri Barbershop">Carregando agendamento...</section>;
  return <section className="mobile-booking-app booking-commerce-app booking-hub-v2 booking-v3" aria-label="Central de agendamento Yuri Barbershop"><div className="booking-v3-top"><div><small>YURI BARBERSHOP</small><strong>{journey==="products"?"Produtos":"Agendamento"}</strong></div>{step!=="home"&&<div><button type="button" onClick={back}>← Voltar</button><button type="button" onClick={home}>Início</button></div>}</div>{message&&<p className="booking-v3-message">{message}</p>}
    {step==="home"&&<><section className="booking-v3-hero"><small>AGENDE EM POUCOS PASSOS</small><h2>O que vamos fazer hoje?</h2><p>Escolha seus serviços, profissional, data e horário.</p><button type="button" onClick={()=>{setJourney("booking");setStep("services")}}>Escolher serviços →</button></section><section className="booking-v3-product-callout"><div><small>PRODUTOS</small><h3>Quer levar algo da barbearia?</h3><p>Escolha os produtos disponíveis e envie seu pedido pelo WhatsApp.</p></div><button type="button" onClick={()=>{setJourney("products");setStep("products")}}>Ver produtos →</button></section></>}
    {step==="services"&&<section><div className="booking-v3-title"><div><small>1. SERVIÇOS</small><h2>Escolha um ou mais serviços</h2></div>{selectedServices.length>0&&<span>{totalDuration} min · {money(serviceTotal)}</span>}</div><div className="booking-v3-service-grid">{data.services.map(s=><button type="button" key={s.id} className={selectedServices.includes(s.id)?"selected":""} onClick={()=>toggleService(s.id)}><span>{selectedServices.includes(s.id)?"✓":"+"}</span><div><strong>{s.name}</strong><small>{s.durationMin} min</small></div><b>{money(s.priceCents)}</b></button>)}</div><button className="booking-v3-next" disabled={!selectedServices.length} onClick={()=>setStep("professional")}>Continuar →</button></section>}
    {step==="professional"&&<section><div className="booking-v3-title"><div><small>2. PROFISSIONAL</small><h2>Quem vai atender?</h2></div></div><div className="booking-v3-choice"><button type="button" className={!collaboratorId?"selected":""} onClick={()=>setCollaboratorId(0)}>Qualquer disponível</button>{data.collaborators.map(c=><button type="button" key={c.id} className={collaboratorId===c.id?"selected":""} onClick={()=>setCollaboratorId(c.id)}>{c.name}</button>)}</div><button className="booking-v3-next" onClick={()=>setStep("datetime")}>Escolher data e horário →</button></section>}
    {step==="datetime"&&<section><div className="booking-v3-title"><div><small>3. DATA E HORÁRIO</small><h2>Quando você quer vir?</h2></div><span>{totalDuration} min</span></div><label className="booking-v3-date">Data<input type="date" min={localDateKey()} value={date} onChange={e=>{setDate(e.target.value);setTime("")}}/></label>{date&&<div className="booking-v3-times">{availableTimes.length?availableTimes.map(t=><button type="button" key={t} className={time===t?"selected":""} onClick={()=>setTime(t)}>{t}</button>):<p>Nenhum horário disponível nessa data.</p>}</div>}<button className="booking-v3-next" disabled={!date||!time} onClick={()=>setStep("details")}>Continuar →</button></section>}
    {step==="products"&&<section><div className="booking-v3-title"><div><small>PRODUTOS DISPONÍVEIS</small><h2>Monte seu pedido</h2></div><span>{money(productTotal)}</span></div><div className="booking-v3-products">{data.products.filter(p=>p.stock>0).map(p=>{const q=cart[p.id]||0;const image=storedImage(p.imageKey);return <article key={p.id}>{image?<img src={image} alt={p.name}/>:<div className="product-placeholder">Y</div>}<div><strong>{p.name}</strong><small>{p.description||"Produto disponível"}</small><b>{money(p.priceCents)}</b><em>{p.stock} em estoque</em></div><div className="booking-v3-qty">{q>0&&<button onClick={()=>updateProduct(p,-1)}>−</button>}<span>{q||""}</span><button onClick={()=>updateProduct(p,1)} disabled={q>=p.stock}>{q?"+":"Adicionar"}</button></div></article>})}</div><button className="booking-v3-next" disabled={!cartItems.length} onClick={()=>setStep("details")}>Revisar pedido →</button></section>}
    {step==="details"&&<section><div className="booking-v3-title"><div><small>{journey==="products"?"DADOS DO PEDIDO":"4. SEUS DADOS"}</small><h2>Como podemos identificar você?</h2></div></div><div className="booking-v3-details"><label>Nome<input value={details.name} onChange={e=>setDetails({...details,name:e.target.value})}/></label><label>Telefone / WhatsApp<input value={details.phone} onChange={e=>setDetails({...details,phone:e.target.value})}/></label><label>Aniversário (opcional)<input type="date" value={details.birthDate} onChange={e=>setDetails({...details,birthDate:e.target.value})}/></label></div><button className="booking-v3-next" disabled={!details.name.trim()||details.phone.replace(/\D/g,"").length<8} onClick={()=>setStep("summary")}>Ver resumo →</button></section>}
    {step==="summary"&&<section><div className="booking-v3-title"><div><small>CONFIRMAÇÃO</small><h2>Confira antes de enviar</h2></div></div><div className="booking-v3-summary">{journey==="booking"?<><div><span>Serviços</span><strong>{services.map(s=>s.name).join(" + ")}</strong></div><div><span>Duração</span><strong>{totalDuration} min</strong></div><div><span>Data e horário</span><strong>{new Date(`${date}T12:00:00`).toLocaleDateString("pt-BR")} às {time}</strong></div><div><span>Profissional</span><strong>{data.collaborators.find(c=>c.id===collaboratorId)?.name||"Qualquer disponível"}</strong></div><div className="total"><span>Total</span><strong>{money(serviceTotal)}</strong></div></>:<>{cartItems.map(i=><div key={i.product.id}><span>{i.quantity}x {i.product.name}</span><strong>{money(i.product.priceCents*i.quantity)}</strong></div>)}<div className="total"><span>Total</span><strong>{money(productTotal)}</strong></div><p>O estoque só será baixado quando o pedido for finalizado no atendimento.</p></>}</div><button className="booking-v3-next whatsapp" disabled={submitting} onClick={()=>void finish()}>{submitting?"Registrando...":journey==="products"?"Registrar e abrir WhatsApp":"Agendar e abrir WhatsApp"} →</button></section>}
  </section>
}
